# Travis CI config for Limba
# unattended full upgrade: sudo apt-get -o Dpkg::Options::="--force-confold" --force-yes -fuy dist-upgrade

language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -qq gettext

before_script:
  - env | sort
  - uname -a
  - chmod +x sweetbuild.sh

script:
  - "./sweetbuild.sh"
